title: Dream Dress Noivas
email: info@dreamdressnoiva.com
description: "Realizando Sonhos"
url: "http://dreamdressnoiva.com"
author: Ivo Zinenda

# Build settings
markdown: kramdown

plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - hawkins
  - jekyll-autolink_email

analytics: 

exclude:
   - bower_components
   - node_modules

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotipo/logo.svg
logo: /assets/img/logotipo/logotype.svg

collections:
  sobre:
  servicos:
  portfolio:
    output: true
  vestidos_noivas:
  vestidos_cerimonias:
  fatos_noivos:
  calcados:
  acessorios:
  slider:

defaults:
- scope:
    path: ""
    type: products
  values:
    title: ""
    image: ""
    price: 0.0
    sku: ""
    weight: 0.0
    layout: products

- scope:
    path: ""
    type: portfolio
  values:
    title:
    image: ""
    images: ""
    layout: portfolio

- scope:
    path: ""
    image: ""
    type: slider
  values:
    title: ""
    image: ""
    min_price: 0.0