title: Dream Dress Noivas
email: info@dreamdressnoiva.com
description: "Realizando Sonhos"
url: "https://dreamdressnoiva.com"
author: Ivo Zinenda

sobre: "A Dream Dress Noivas é uma distribuidora nacional (moçambicana) de artigos para casamentos, desde vestidos, fatos e vários acessórios. Confie na Dream Dress Noivas, porque a sua satisfação também é a nossa."

# Build settings
markdown: kramdown

plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - hawkins
  - jekyll-autolink_email

analytics: 

exclude:
   - bower_components
   - node_modules

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotipo/logo.svg
logo: /assets/img/logotipo/logotype.svg

collections:
  sobre:
  servicos:
  portfolio:
  productos:
    output: true

defaults:
  - scope:
      path: ""
      image: ""
      price:
      description:
      type: productos
    values:
      layout: page