title: Dream Dress Noivas
email: info@dreamdressnoiva.com
description: "Realizando Sonhos"
url: "https://dreamdressnoiva.com"
author: Ivo Zinenda

# Build settings
markdown: kramdown

plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - hawkins
  - jekyll-autolink_email

analytics: 

exclude:
   - bower_components
   - node_modules

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotype.svg
logo: /assets/img/logo.svg

first_title: "Sobre"
first_description: "Este o modelo exemplar para websites do Pacote startUP da IZItag.
startUP é um pacote acessível que permitirá a empresas iniciantes e de pequeno porte possam ter uma presença online sem
altos custos assim como grandes corporações"

second_title: "Serviços"
second_description:

thirth_title: "Portfólio"
thirth_description:

primary-color: "#cc3333"
secondary-color: "#444"

collections:
  servicos:
  portfolio: