# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: StartUp-Template
email: info@izitag.site
description: "StartUp é um pacote para de websites criado para empresas
 iniciantes que não podem investir massas de dinheiro para websites dinâmicos, 
 todavia querem ter presença online"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - hawkins
  - jekyll-autolink_email
  - uglifier

exclude:
   - bower_components

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

img_dir: /assets/img
js_dir: /assets/js

image: 
logo:

first_parallax:
second_parallax:
thirth_parallax:

first_title: ""
second_title: ""
thirth_title: ""