---
pages:
- _productos/vestidos.md
- _productos/livraria.md
- _productos/fatos.md
- _productos/decoracao.md
- _productos/calcados.md
- _productos/acessorios.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: price
  label: Price
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: file
  name: image
  label: Image
- name: layout
  label: Layout
  type: text
  hidden: false
  default: page
