---
pages:
- _vestidos_noivas/floariana.md
- _vestidos_noivas/cereia-justo.md
- _vestidos_noivas/vestido-tradiconal.md
- _vestidos_noivas/vestido-de-cereia.md
- _acessorios/tacas.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: price
  label: Price
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: file
  name: image
  label: Image
- name: layout
  label: Layout
  type: text
  hidden: false
  default: page
