---
pages:
- _acessorios/buque-sintetico-prata.md
- _acessorios/buque-de-rosas-brancas-vermelhas.md
- _acessorios/cestinho-de-coletas.md
- _acessorios/jogo-de-tacas.md
- _acessorios/duas-tacas-de-brinde.md
- _acessorios/conjunto-de-tacas-facas.md
- _acessorios/penas-de-assinatura.md
hide_body: false
fields:
- name: title
  label: Nome do Produto
  type: text
  hidden: false
  default: ''
- name: price
  label: Preço
  type: text
  hidden: false
  default: '0'
- name: sku
  label: Referencia
  type: text
  hidden: false
  default: ''
  description: Digite a referencia do produto
  config:
    required: false
- name: weight
  label: Quantidade
  type: text
  hidden: false
  default: '0'
- type: file
  name: image
  label: Imagem
- name: layout
  label: Layout
  type: text
  hidden: false
  default: products
